plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/sergiuman/Desktop/Gemini/Carti Sofia 5/sofia-learning-hub/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]